services:
  memgpt_db:
    image: ankane/pgvector:v0.5.1
    hostname: memgpt-db
    environment:
      - POSTGRES_USER=${MEMGPT_PG_USER}
      - POSTGRES_PASSWORD=${MEMGPT_PG_PASSWORD}
      - POSTGRES_DB=${MEMGPT_PG_DB}
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  memgpt_server:
    image: memgpt_server
    hostname: memgpt-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MEMGPT_ENVIRONMENT=DEVELOPMENT
    depends_on:
      - memgpt_db
    ports:
      - "8083:8083"
      - "8283:8283"
    env_file:
      - .env
    volumes:
      - ./memgpt:/memgpt
      - ./tests:/tests
      - ./configs/server_config.yaml:/root/.memgpt/config # config file
      - ~/.memgpt/credentials:/root/.memgpt/credentials # credentials file
  memgpt_nginx:
    hostname: memgpt-nginx
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"