services:
  memgpt_db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=${MEMGPT_PG_USER}
      - POSTGRES_PASSWORD=${MEMGPT_PG_PASSWORD}
      - POSTGRES_DB=${MEMGPT_PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  memgpt_server:
    image: memgpt_server
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn memgpt.server.rest_api.server:app --reload --reload-dir /memgpt --host 0.0.0.0 --port 8083
    depends_on:
      - memgpt_db
    ports:
      - "8083:8083"
      - "8283:8283"
    env_file:
      - .env
    volumes:
      - ./memgpt:/memgpt
      - ./configs/server_config.yaml:/root/.memgpt/config # config file
      - ~/.memgpt/credentials:/root/.memgpt/credentials # credentials file
  memgpt_nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"