site_name: MemGPT
site_url: https://memgpt.ai
nav:
  - Home: index.md
  - 'User Guide':
    - quickstart.md
    - config.md
    - data_sources.md
  - 'Local LLMs':
    - webui.md
    - lmstudio.md
    - custom_llm.md
  - 'Advanced'
  - About: about.md
theme: readthedocs
