site_name: MemGPT
site_url: https://memgpt.ai
nav:
  - Home: index.md
  - 'User Guide':
    - quickstart.md
    - config.md
    - data_sources.md
    - cli_faq.md
  - 'Discord Bot':
    - setup.md
    - discord_bot_faq.md
  - 'Local LLM':
    - llm_backend.md
    - webui.md
    - lmstudio.md
    - custom_llm.md
    - local_llm_faq.md
  - 'Advanced':
    - adding_wrappers.md
theme: readthedocs
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - json
  #   - python
# include_homepage_in_sidebar: false