site_name: MemGPT
site_url: https://memgpt.ai/
nav:
  - Home: index.md
  - 'User Guide':
    - 'Quickstart': quickstart.md
    - 'Example - perpetual chatbot': example_chat.md
    - 'Example - chat with your data': example_data.md
    - 'Configuration': config.md
    - 'LLM Endpoints': endpoints.md
    - 'External Data Sources': data_sources.md
    - 'FAQ': cli_faq.md
  - 'Discord Bot':
    - setup.md
    - discord_bot_faq.md
  - 'Local LLM':
    - llm_backend.md
    - webui.md
    - lmstudio.md
    - custom_llm.md
    - local_llm_faq.md
  - 'Advanced':
    - 'Configuring Storage Backends': storage.md
    - adding_wrappers.md
  - 'Contributing': contributing.md
theme: readthedocs
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - json
  #   - python
# include_homepage_in_sidebar: false
